// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa2UeTSZLdUEpUlNoRQJfLq9r7gL0qK28',
    appId: '1:839542348635:web:e1e43fd19c19728605187e',
    messagingSenderId: '839542348635',
    projectId: 'login-app-98fc2',
    authDomain: 'login-app-98fc2.firebaseapp.com',
    storageBucket: 'login-app-98fc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzU7_kSNK342YmpMMvCvS6zXMIEYmUDVw',
    appId: '1:839542348635:android:55a12a416a3c0cb905187e',
    messagingSenderId: '839542348635',
    projectId: 'login-app-98fc2',
    storageBucket: 'login-app-98fc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQ3A-kMUQAqqRW2Mhoslo4abAEG3vCAM',
    appId: '1:839542348635:ios:c8443e78a463c5ab05187e',
    messagingSenderId: '839542348635',
    projectId: 'login-app-98fc2',
    storageBucket: 'login-app-98fc2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQ3A-kMUQAqqRW2Mhoslo4abAEG3vCAM',
    appId: '1:839542348635:ios:b9c3230cd5e0020f05187e',
    messagingSenderId: '839542348635',
    projectId: 'login-app-98fc2',
    storageBucket: 'login-app-98fc2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );

  
}
